spring:
  # Spring AI
  ai:
  # Open AI
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
        enabled: true
  # Mistral AI
    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-large-latest
        enabled: false

  threads:
    virtual:
      enabled: true

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5434/vector_store
    username: postgres
    password: postgres
